---
# clone git repo
- name: Clone repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ ansible_env.HOME }}/{{ repo_name }}"

# build shortage harvester container
- name: copy template config.yaml file
  become: true
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: "{{ ansible_env.HOME }}/{{ repo_name }}/mastodon_harvesters/shortage_harvester/config.yaml"
  vars:
    url: "{{ shortage_harvester.url[  item[0]  ] }}"
    api_key: "{{ shortage_harvester.api_key[  item[0]  ] }}"
    ip: "{{ prod | ternary( ansible_hostname , shortage_harvester.db_ip[  item[0]  ] ) }}"
  with_indexed_items: "{{ ansible_play_batch }}"
  when: item[1] == ansible_host

- name: Build Docker image
  become: true
  shell: docker build -t shortage_harvester {{ ansible_env.HOME }}/{{ repo_name }}/mastodon_harvesters/shortage_harvester

# build entities harvester container
- name: copy template config.yaml file
  become: true
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: "{{ ansible_env.HOME }}/{{ repo_name }}/mastodon_harvesters/entities_harvester/config.yaml"
  vars:
    url: "{{ entities_harvester.url[  item[0]  ] }}"
    api_key: "{{ entities_harvester.api_key[  item[0]  ] }}"
    ip: "{{ prod | ternary( ansible_hostname , entities_harvester.db_ip[  item[0]  ] ) }}"

  with_indexed_items: "{{ ansible_play_batch }}"
  when: item[1] == ansible_host

- name: Build Docker image
  become: true
  shell: docker build -t entities_harvester {{ ansible_env.HOME }}/{{ repo_name }}/mastodon_harvesters/entities_harvester

# build hashtag harvester container
- name: copy template config.yaml file
  become: true
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: "{{ ansible_env.HOME }}/{{ repo_name }}/mastodon_harvesters/hashtag_harvester/config.yaml"
  vars:
    url: "{{ hashtag_harvester.url[  item[0]  ] }}"
    api_key: "{{ hashtag_harvester.api_key[  item[0]  ] }}"
    ip: "{{ prod | ternary( ansible_hostname , hashtag_harvester.db_ip[  item[0]  ] ) }}"

  with_indexed_items: "{{ ansible_play_batch }}"
  when: item[1] == ansible_host

- name: Build Docker image
  become: true
  shell: docker build -t hashtag_harvester {{ ansible_env.HOME }}/{{ repo_name }}/mastodon_harvesters/hashtag_harvester

# run all harvesters

- name: Run shortage_harvester container
  become: true
  shell: docker run -d shortage_harvester

- name: Run entity harvester container
  become: true
  shell: docker run -d entities_harvester

- name: Run hashtag harvester container
  become: true
  shell: docker run -d hashtag_harvester