---
- name: Update apt
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Install pip
  become: true
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"