---
# Install dependencies on the host
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  ansible.builtin.pip:
    name: ["pip", "openstacksdk"]
    state: latest


# uncomment this task to use older version of openstacksdk
- name: Install openstacksdk
  ansible.builtin.pip:
    name: ["openstacksdk==0.61.0"]
