---
# Create an instance on NeCTAR
- name: Create couchdb instances
  openstack.cloud.server:
    name: "{{ item.name }}"
    # auto_floating_ip: false
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ instance_flavor }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    # network: "{{ instance_network }}"
    security_groups: "{{ sg_names }}"
    timeout: 600
    # volumes: "{{ item.volumes }}"
    state: present
    wait: true
  loop: "{{ couchdb_instances }}"
  register: os_instance

- ansible.builtin.debug:
    msg: "Couchdb instance {{ item.server.name }} has been created. IP address is {{ item.server.addresses['qh2-uom-internal'][0].addr }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined

# Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: "{{ item.server.addresses['qh2-uom-internal'][0].addr }}"
    groups: couchdb
  loop: "{{ os_instance.results }}"
  when: item.server is defined

- name: Set master
  set_fact:
    master: "{{ groups['couchdb'][0] }}"

 

# Create web instances
- name: Create web instance
  openstack.cloud.server:
    name: "{{ item.name }}"
    # auto_floating_ip: false
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ instance_flavor }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    # network: "{{ instance_network }}"
    security_groups: "{{ sg_names }}"
    timeout: 600
    # volumes: "{{ item.volumes }}"
    state: present
    wait: true
  loop: "{{ web_instances }}"
  register: web_results
  when: create_web == true

- ansible.builtin.debug:
    msg: "Web instance {{ item.server.name }} has been created. IP address is {{ item.server.addresses['qh2-uom-internal'][0].addr }}"
  loop: "{{ web.results }}"
  when: item.server is defined

  # Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: "{{ item.server.addresses['qh2-uom-internal'][0].addr }}"
    groups: web
  loop: "{{ web_results.results }}"
  when: item.server is defined

