---
# Create an instance on NeCTAR
- name: Create couchdb instances
  openstack.cloud.server:
    name: "{{ item.name }}"
    # auto_floating_ip: false
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ instance_flavor }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    # network: "{{ instance_network }}"
    security_groups: "{{ sg_names }}"
    timeout: 600
    # volumes: "{{ item.volumes }}"
    state: present
    wait: true
  loop: "{{ couchdb_instances }}"
  register: os_instance

- ansible.builtin.debug:
    msg: "Couchdb instance {{ item.server.name }} has been created. IP address is {{ item.server.addresses['qh2-uom-internal'][0].addr }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined

# comment this section out if not connected to unimelb network
# - name: Wait for connection
#   ansible.builtin.wait_for:
#     host: "{{ item.server.addresses['qh2-uom-internal'][0].addr }}"
#     port: 22
#     timeout: 120
#     search_regex: OpenSSH
#   loop: "{{ os_instance.results }}"
#   when: item.server is defined

# Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: "{{ item.server.addresses['qh2-uom-internal'][0].addr }}"
    groups: couchdb_instances
  loop: "{{ os_instance.results }}"
  when: item.server is defined



# Create web instances
- name: Create web instance
  openstack.cloud.server:
    name: "{{ item.name }}"
    # auto_floating_ip: false
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ instance_flavor }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    # network: "{{ instance_network }}"
    security_groups: "{{ sg_names }}"
    timeout: 600
    # volumes: "{{ item.volumes }}"
    state: present
    wait: true
  loop: "{{ couchdb_instances }}"
  register: web_instance

- ansible.builtin.debug:
    msg: "Web instance {{ item.server.name }} has been created. IP address is {{ item.server.addresses['qh2-uom-internal'][0].addr }}"
  loop: "{{ web_instance.results }}"
  when: item.server is defined

  # Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: "{{ item.server.addresses['qh2-uom-internal'][0].addr }}"
    groups: web_instances
  loop: "{{ web_instance.results }}"
  when: item.server is defined