---
# install docker
- name: Install docker required apt packages
  become: true
  ansible.builtin.apt:
    name: ['apt-transport-https', 'ca-certificates', 'software-properties-common', 'gnupg-agent']
    state: latest
    update_cache: yes

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up stable version for apt repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    state: present

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli'] #,'containerd.io']
    state: latest
    update_cache: yes

# install docker compose
- name: Install docker-compose
  become: true
  pip:
    name: ['docker-compose']
    state: latest