# # install couchdb 
# - hosts: couchdb
#   vars_files:
#     - vars/couchdb.yaml
#   gather_facts: true

#   roles:
#     - role: common
#     - role: docker
#     - role: couchdb

# # set up couchdb cluster
# - hosts: master
#   vars_files:
#     - vars/couchdb.yaml
#   gather_facts: true
#   roles:
#     - role: couch-cluster

# # set up mastodon harvesters
# - hosts: couchdb 
#   vars_files:
#     - vars/couchdb.yaml
#     - vars/mastodon.yaml
#   roles: 
#     - role: mastodon_harvester

# set up webserver
- hosts: web
  vars_files:
    - vars/couchdb.yaml
    - vars/mastodon.yaml
  gather_facts: true
  roles:
    - role: deploy-web