# # create cloud instances
# - hosts: localhost
#   vars_files:
#     - vars/mrc.yaml
#   gather_facts: true

#   roles:
#     - role: openstack-common
# #     - role: openstack-volume
#     - role: openstack-security-group
#     - role: openstack-instance

#  install couchdb 
# - hosts: couchdb
#   vars_files:
#     - vars/couchdb.yaml
#   gather_facts: true

#   roles:
#     - role: common
#     - role: docker
#     - role: couchdb

# set up couchdb cluster
# - hosts: master
#   vars_files:
#     - vars/couchdb.yaml
#   gather_facts: true
#   roles:
#     - role: couch-cluster

# set up mastodon harvesters
- hosts: couchdb 
  vars_files:
    - vars/couchdb.yaml
    - vars/mastodon.yaml
  roles: 
    - role: mastodon_harvester


# set up webserver