# create cloud instances
- hosts: localhost
  vars_files:
    - vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
#     - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
