# create cloud instances
- hosts: localhost
  vars_files:
    - vars/scale-up.yaml
  gather_facts: true
  roles:
    - role: openstack-common
    - role: openstack-security-group
    - role: openstack-instance

    