# install couchdb and mastodon harvesters
- hosts: couchdb
  vars_files:
    - vars/couchdb.yaml
    - vars/mastodon.yaml
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: couchdb
    - role: mastodon_harvester

    