# create cloud instances
- hosts: localhost
  vars_files:
    - vars/scale-up.yaml
  gather_facts: true
  roles:
    - role: openstack-common
    - role: openstack-security-group
    - role: openstack-instance

# install couchdb and mastodon harvesters
- hosts: couchdb
  vars_files:
    - vars/couchdb.yaml
    - vars/mastodon.yaml
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: couchdb
    - role: mastodon_harvester

    